import {render,screen,fireEvent,waitFor,cleanup} from '@testing-library/react'
import {QueryClient,QueryClientProvider} from '@tanstack/react-query'
import {MemoryRouter} from 'react-router-dom'
import {afterEach,expect,it,vi} from 'vitest'
import {ChengyuTasksPage} from './ChengyuTasksPage'
afterEach(()=>{cleanup();vi.unstubAllGlobals()})
const task={id:1,title:'成语测试',count:1,types:['meaning'],createdAt:'2026-09-15',items:[{id:'q1',kind:'meaning',skillCode:'meaning',targetId:1,sourceId:1,sourceTable:'knowledge_points',moduleCode:'daily',sourceContentHash:'abc123',example:{kind:'meaning',speech:'一心一意',speechUrl:'/api/v1/chengyu/task-media/abc.mp3',options:[{id:'label:集中精神，做事专心',label:'集中精神，做事专心'},{id:'label:心思不专一',label:'心思不专一'},{id:'label:慢慢来',label:'慢慢来'},{id:'label:随便玩玩',label:'随便玩玩'}],answerId:'label:集中精神，做事专心'},mediaSHA256:{'/api/v1/chengyu/items/1/speech.mp3':'abc'}}]}
function page(){render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><MemoryRouter><ChengyuTasksPage/></MemoryRouter></QueryClientProvider>)}
it('opens saved question, previews locally and restores focus on Escape',async()=>{
 const fetcher=vi.fn(async(url:string,_init?:RequestInit)=>({ok:true,status:200,json:async()=>url.endsWith('/1')?task:{items:[task]}} as Response));vi.stubGlobal('fetch',fetcher);page();const trigger=await screen.findByRole('button',{name:/成语测试/});trigger.focus();fireEvent.click(trigger);await screen.findByRole('button',{name:'集中精神，做事专心'});fireEvent.click(screen.getByRole('button',{name:'集中精神，做事专心'}));expect(screen.getByText('答对了')).toBeInTheDocument();expect(fetcher.mock.calls.every(c=>c.length===1||!(c[1] as RequestInit)?.method||(c[1] as RequestInit)?.method==='GET')).toBe(true);fireEvent(await screen.findByRole('dialog'),new Event('cancel',{bubbles:true,cancelable:true}));await waitFor(()=>expect(screen.queryByRole('dialog')).not.toBeInTheDocument());expect(trigger).toHaveFocus();expect(screen.queryByText('发布')).not.toBeInTheDocument()
})
it('generates selected types then loads persisted task detail',async()=>{
 const calls:{url:string;init?:RequestInit}[]=[];vi.stubGlobal('fetch',vi.fn(async(url:string,init?:RequestInit)=>{calls.push({url,init});return {ok:true,status:200,json:async()=>init?.method==='POST'||url.endsWith('/1')?task:{items:[]}} as Response}));page();await screen.findByText('暂无成语出题任务。');fireEvent.click(screen.getByRole('button',{name:'生成成语题目'}));fireEvent.click(screen.getByRole('button',{name:'生成并保存'}));await screen.findByRole('button',{name:'集中精神，做事专心'});const post=calls.find(c=>c.init?.method==='POST');expect(JSON.parse(post!.init!.body as string)).toMatchObject({count:4,types:['meaning','pick','pinyin','example']});expect(calls.some(c=>c.url.endsWith('/1')&&c.init?.method==='GET')).toBe(true)
})
it('shows load failure without claiming an empty list',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>({ok:false,status:503,json:async()=>({error:'成语任务服务未配置'})})));page();expect(await screen.findByRole('alert')).toHaveTextContent('成语任务服务未配置');expect(screen.queryByText('暂无成语出题任务。')).not.toBeInTheDocument()}
)