import {render,screen,fireEvent,waitFor,cleanup} from '@testing-library/react'
import {QueryClient,QueryClientProvider} from '@tanstack/react-query'
import {MemoryRouter} from 'react-router-dom'
import {afterEach,expect,it,vi} from 'vitest'
import {EnglishTasksPage} from './EnglishTasksPage'
afterEach(()=>{cleanup();vi.unstubAllGlobals()})
const task={id:1,title:'英语测试',count:1,types:['audio-choice'],createdAt:'2026-09-13',items:[{id:'q1',kind:'audio-choice',skillCode:'listen',targetId:1,sourceId:1,sourceTable:'english_assets',moduleCode:'animals',sourceContentHash:'abc123',example:{kind:'audio-choice',speech:'apple',speechUrl:'/api/v1/english/task-media/abc.mp3',options:[{id:'1',label:'苹果'},{id:'2',label:'小狗'},{id:'3',label:'小猫'},{id:'4',label:'小鸟'}],answerId:'1'},mediaSHA256:{'/source':'abc'}}]}
const typeTask={id:2,title:'写单词',count:1,types:['input-gap'],createdAt:'2026-09-13',items:[{id:'q1',kind:'input-gap',skillCode:'type',targetId:1,sourceId:1,sourceTable:'english_assets',moduleCode:'animals',sourceContentHash:'hash-apple',example:{kind:'input-gap',prompt:'写出这个单词',speech:'apple',speechUrl:'/a.mp3',cue:'/cue.jpg',answer:'apple'},mediaSHA256:{'/cue.jpg':'bbbb'}}]}
const tileTask={id:3,title:'组句子',count:1,types:['card-builder'],createdAt:'2026-09-13',items:[{id:'q1',kind:'card-builder',skillCode:'build',targetId:1,sourceId:11,sourceTable:'english_sentences',moduleCode:'animals',sourceContentHash:'hash-sent',example:{kind:'card-builder',prompt:'把单词排成一句话',speech:'This is an apple',speechUrl:'/s.mp3',bank:['apple','This','an','is'],answer:'This is an apple'},mediaSHA256:{'/s.mp3':'cccc'}}]}
function page(){render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><MemoryRouter><EnglishTasksPage/></MemoryRouter></QueryClientProvider>)}
it('opens saved question, previews locally and restores focus on Escape',async()=>{
 const fetcher=vi.fn(async(url:string,_init?:RequestInit)=>({ok:true,status:200,json:async()=>url.endsWith('/1')?task:{items:[task]}} as Response));vi.stubGlobal('fetch',fetcher);page();const trigger=await screen.findByRole('button',{name:/英语测试/});trigger.focus();fireEvent.click(trigger);await screen.findByRole('button',{name:'苹果'});fireEvent.click(screen.getByRole('button',{name:'苹果'}));expect(screen.getByText('答对了')).toBeInTheDocument();expect(fetcher.mock.calls.every(c=>c.length===1||!(c[1] as RequestInit)?.method||(c[1] as RequestInit)?.method==='GET')).toBe(true);fireEvent(await screen.findByRole('dialog'),new Event('cancel',{bubbles:true,cancelable:true}));await waitFor(()=>expect(screen.queryByRole('dialog')).not.toBeInTheDocument());expect(trigger).toHaveFocus();expect(screen.queryByText('发布')).not.toBeInTheDocument()
})
it('lets preview submit a typed word without writing learning records',async()=>{
 const fetcher=vi.fn(async(url:string,_init?:RequestInit)=>({ok:true,status:200,json:async()=>url.endsWith('/2')?typeTask:{items:[typeTask]}} as Response));vi.stubGlobal('fetch',fetcher);page();fireEvent.click(await screen.findByRole('button',{name:/写单词/}));fireEvent.change(await screen.findByRole('textbox',{name:'单词'}),{target:{value:'aple'}});fireEvent.click(screen.getByRole('button',{name:'写好了'}));expect(screen.getByText('再试一次')).toBeInTheDocument();fireEvent.change(screen.getByRole('textbox',{name:'单词'}),{target:{value:'apple'}});fireEvent.click(screen.getByRole('button',{name:'写好了'}));expect(screen.getByText('答对了')).toBeInTheDocument();expect(screen.getByText(/内容摘要 hash-apple/)).toBeInTheDocument();expect(screen.queryByText(/素材版本/)).not.toBeInTheDocument();expect(fetcher.mock.calls.every(c=>!c[1]?.method||c[1].method==='GET')).toBe(true)
})
it('lets preview check a built sentence and retry',async()=>{
 vi.stubGlobal('fetch',vi.fn(async(url:string)=>({ok:true,status:200,json:async()=>url.endsWith('/3')?tileTask:{items:[tileTask]}} as Response)));page();fireEvent.click(await screen.findByRole('button',{name:/组句子/}));for(const token of ['This','is','an','apple']) fireEvent.click(await screen.findByRole('button',{name:token}));expect(screen.getByText('答对了')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'重来'}));expect(screen.queryByText('答对了')).not.toBeInTheDocument()
})
it('generates selected types then loads persisted task detail',async()=>{
 const calls:{url:string;init?:RequestInit}[]=[];vi.stubGlobal('fetch',vi.fn(async(url:string,init?:RequestInit)=>{calls.push({url,init});return {ok:true,status:200,json:async()=>init?.method==='POST'||url.endsWith('/1')?task:{items:[]}} as Response}));page();await screen.findByText('暂无英语出题任务。');fireEvent.click(screen.getByRole('button',{name:'生成英语题目'}));fireEvent.click(screen.getByRole('button',{name:'生成并保存'}));await screen.findByRole('button',{name:'苹果'});const post=calls.find(c=>c.init?.method==='POST');expect(JSON.parse(post!.init!.body as string)).toMatchObject({count:5,types:['audio-choice','image-text','card-builder','input-gap','reading-qa']});expect(calls.some(c=>c.url.endsWith('/1')&&c.init?.method==='GET')).toBe(true)
})
it('shows load failure without claiming an empty list',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>({ok:false,status:503,json:async()=>({error:'英语任务服务未配置'})})));page();expect(await screen.findByRole('alert')).toHaveTextContent('英语任务服务未配置');expect(screen.queryByText('暂无英语出题任务。')).not.toBeInTheDocument()}
)