import {render,screen,fireEvent,waitFor,cleanup} from '@testing-library/react'
import {QueryClient,QueryClientProvider} from '@tanstack/react-query'
import {afterEach,expect,it,vi} from 'vitest'
import {PinyinTasksPage} from './PinyinTasksPage'
afterEach(()=>{cleanup();vi.unstubAllGlobals()})
const task={id:1,title:'拼音测试',count:1,types:['listen'],createdAt:'2026-09-13',items:[{id:'q1',type:'listen',stem:'听一听，选出你听到的拼音',targetId:1,sourceTable:'pinyin_assets',moduleCode:'initial',speechUrl:'/api/v1/pinyin/task-media/abc.mp3',visual:{kind:'sound'},options:[{id:'1',label:'b'},{id:'2',label:'p'},{id:'3',label:'m'},{id:'4',label:'f'}],answerOptionId:'1',mediaSHA256:{'/source':'abc'}}]}
function page(){render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><PinyinTasksPage/></QueryClientProvider>)}
it('opens saved question, previews locally and restores focus on Escape',async()=>{
 const fetcher=vi.fn(async(url:string,_init?:RequestInit)=>({ok:true,status:200,json:async()=>url.endsWith('/1')?task:{items:[task]}} as Response));vi.stubGlobal('fetch',fetcher);page();const trigger=await screen.findByRole('button',{name:/拼音测试/});trigger.focus();fireEvent.click(trigger);await screen.findByRole('button',{name:'b'});fireEvent.click(screen.getByRole('button',{name:'b'}));expect(screen.getByText('答对啦')).toBeInTheDocument();expect(fetcher.mock.calls.every(c=>c.length===1||!(c[1] as RequestInit)?.method||(c[1] as RequestInit)?.method==='GET')).toBe(true);fireEvent(await screen.findByRole('dialog'),new Event('cancel',{bubbles:true,cancelable:true}));await waitFor(()=>expect(screen.queryByRole('dialog')).not.toBeInTheDocument());expect(trigger).toHaveFocus();expect(screen.queryByText('发布')).not.toBeInTheDocument()
})
it('generates selected types then loads persisted task detail',async()=>{
 const calls:{url:string;init?:RequestInit}[]=[];vi.stubGlobal('fetch',vi.fn(async(url:string,init?:RequestInit)=>{calls.push({url,init});return {ok:true,status:200,json:async()=>init?.method==='POST'||url.endsWith('/1')?task:{items:[]}} as Response}));page();await screen.findByText('暂无拼音出题任务。');fireEvent.click(screen.getByRole('button',{name:'生成拼音题目'}));fireEvent.click(screen.getByRole('button',{name:'生成并保存'}));await screen.findByRole('button',{name:'b'});const post=calls.find(c=>c.init?.method==='POST');expect(JSON.parse(post!.init!.body as string)).toMatchObject({count:8,types:['listen','inword','shape','blend']});expect(calls.some(c=>c.url.endsWith('/1')&&c.init?.method==='GET')).toBe(true)
})
it('shows load failure without claiming an empty list',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>({ok:false,status:503,json:async()=>({error:'拼音任务服务未配置'})})));page();expect(await screen.findByRole('alert')).toHaveTextContent('拼音任务服务未配置');expect(screen.queryByText('暂无拼音出题任务。')).not.toBeInTheDocument()})
