import { BackToList, useListReturn } from '../lib/listNavigation'
import { useInfiniteQuery,useQuery } from '@tanstack/react-query'
import { Link,useParams,useSearchParams } from 'react-router-dom'
import { knowledge,queryString,statusLabel,timeLabel,followLabel } from '../api/knowledge'
import type { Evidence,Page,Point } from '../api/knowledgeTypes'
import { getChildId } from '../store/childStore'
import { LoadState,MoreButton } from '../components/knowledge/Shared'
export function KpArchivePage(){const returnState=useListReturn();const{kpId=''}=useParams();const child=getChildId();const[params,setParams]=useSearchParams();const result=params.get('result')||''
 const point=useQuery({queryKey:['knowledge','point',child,kpId],queryFn:()=>knowledge<Point>(`/points/${kpId}`)})
 const history=useInfiniteQuery({queryKey:['knowledge','history',child,kpId,result],initialPageParam:'',queryFn:({pageParam})=>knowledge<Page<Evidence>>(`/points/${kpId}/attempts`+queryString({cursor:pageParam,result})),getNextPageParam:p=>p.hasMore?p.nextCursor:undefined})
 const p=point.data;return <article><p className="crumb"><BackToList fallback="/library" label="返回列表"/> / 知识点档案</p><LoadState loading={point.isPending} error={point.error}/>{p&&<><header className="page-head"><div><p className="eyebrow">{p.subjectName} · {p.moduleName}</p><h1 className="archive-title">{p.title}</h1><p className="lede">{p.stats.observedAttempts} 次真实练习 · {p.wrongCount} 次错误</p></div><Link className="primary-link" to={`/reviews?subject=${p.subjectCode}&kpId=${p.kpId}`}>查看复习建议</Link></header>
 <section className="panel"><h2>已经会的能力，与还在练的部分</h2><div className="ability-grid">{p.skills.map(sk=><div key={sk.skillCode} className={`ability-card state-${sk.masteryStatus}`}><span className="ability-dot"/><h3>{sk.label}</h3><strong>{statusLabel(sk.masteryStatus)}</strong><p>{sk.stats.observedAttempts?`已练 ${sk.stats.observedAttempts} 次，答对 ${sk.stats.observedCorrect} 次`:'暂无作答明细'}</p>{sk.stats.assistedAttempts>0&&<small>其中 {sk.stats.assistedAttempts} 次使用提示</small>}{sk.evidenceCoverage==='missing'&&sk.masteryStatus!=='not_started'&&<small>账本已有状态，历史明细不完整</small>}</div>)}</div>{p.skills.length===0&&<p>{statusLabel(p.masteryStatus)} · 该学科按知识点记录</p>}</section>
 <section className="panel"><div className="section-heading"><h2>作答记录</h2><div className="segmented"><button className={!result?'active':''} onClick={()=>setParams({})}>全部</button><button className={result==='wrong'?'active':''} onClick={()=>setParams({result:'wrong'})}>只看错误</button></div></div><LoadState loading={history.isPending} error={history.error}/><div className="attempt-list">{history.data?.pages.flatMap(x=>x.items).map(e=><Link key={e.attemptId} state={returnState()} to={`/attempts/${e.attemptId}`} className="attempt-row"><span className={`result-mark ${e.isCorrect?'ok':'wrong'}`}>{e.isCorrect?'对':'错'}</span><div><strong>{e.skillLabel}</strong><p>{e.assistance==='hinted'?'使用了提示 · ':''}{!e.isCorrect?followLabel(e.followUpState):'已记录这次作答'}</p></div><time>{timeLabel(e.occurredAt)}</time><span>查看 ↗</span></Link>)}</div>{history.data?.pages[0].items.length===0&&<p className="empty">没有对应的作答记录。</p>}<MoreButton more={!!history.hasNextPage} loading={history.isFetchingNextPage} onClick={()=>void history.fetchNextPage()}/></section></>}</article>}
