import { expect, test } from './fixture'

test('a failed submission stays frozen, retries the same identity and counts once', async ({ page, mockAPI }) => {
  mockAPI.failNextAnswer = 'before-write'
  await page.goto('/practice/type/listen')
  await page.getByRole('button', { name: 'p', exact: true }).click()
  await expect(page.getByRole('button', { name: '重试提交' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'b', exact: true })).toBeDisabled()
  await expect(page.getByLabel('下一题')).toHaveAttribute('aria-disabled', 'true')
  expect(mockAPI.ledger).toHaveLength(0)
  await page.getByRole('button', { name: '重试提交' }).click()
  await expect(page).toHaveURL('/practice/type/listen/2')
  expect(mockAPI.submissions).toHaveLength(2)
  expect(mockAPI.submissions[1]).toEqual(mockAPI.submissions[0])
  expect(mockAPI.ledger).toHaveLength(1)
  await page.getByRole('link', { name: '上一题' }).click()
  await expect(page.getByRole('button', { name: 'p', exact: true })).toBeDisabled()
})

test('an accepted response lost in transit is recovered by refresh without another submission', async ({ page, mockAPI }) => {
  mockAPI.failNextAnswer = 'after-write'
  await page.goto('/practice/type/listen')
  await page.getByRole('button', { name: 'p', exact: true }).click()
  await expect(page.getByRole('button', { name: '重试提交' })).toBeVisible()
  expect(mockAPI.ledger).toHaveLength(1)
  await page.reload()
  await expect(page.getByRole('button', { name: 'p', exact: true })).toBeDisabled()
  await expect(page.getByRole('progressbar', { name: '听音选字母，1 / 4' })).toBeVisible()
  expect(mockAPI.reads).toHaveLength(4)
  expect(mockAPI.submissions).toHaveLength(1)
  expect(mockAPI.ledger).toHaveLength(1)
})

test('blend submits the selected asset option ID and retains the distinct server knowledge point', async ({ page, mockAPI }) => {
  await page.goto('/practice/type/blend')
  await expect(page.getByRole('button', { name: '选择读音 2' })).toBeDisabled()
  await page.getByRole('button', { name: '播放读音 2' }).click()
  expect(mockAPI.submissions).toHaveLength(0)
  await page.getByRole('button', { name: '选择读音 2' }).click()
  await expect(page).toHaveURL('/practice/type/blend/2')
  expect(mockAPI.submissions[0].input.optionId).toBe('701')
  expect(mockAPI.ledger).toEqual([{ childId: 1, kpId: 9701, type: 'blend', optionId: '701' }])
  const stored = await page.evaluate(() => JSON.parse(localStorage.getItem('pinyin-practice:v1:1:blend')!))
  expect(stored.entries[0].result.knowledge.kpId).toBe(9701)
  expect(stored.entries[0].result.skill.code).toBe('blend')
  expect(stored.entries[0].question).not.toHaveProperty('answerIndex')
})

test('skipping never submits or reveals answers; retry practice generates fresh instances', async ({ page, mockAPI }) => {
  await page.goto('/practice/type/listen/4')
  await page.getByRole('link', { name: '下一题' }).click()
  await expect(page.getByRole('heading', { name: '答题结果' })).toBeVisible()
  await expect(page.getByText('未作答', { exact: true })).toHaveCount(4)
  await expect(page.getByText(/正确答案/)).toHaveCount(0)
  expect(mockAPI.submissions).toHaveLength(0)
  expect(mockAPI.ledger).toHaveLength(0)
  const previousIds = [...mockAPI.instances.keys()]
  await page.getByRole('link', { name: '再练一次' }).click()
  await expect(page.getByRole('button', { name: 'p', exact: true })).toBeEnabled()
  expect(mockAPI.generated).toHaveLength(8)
  const stored = await page.evaluate(() => JSON.parse(localStorage.getItem('pinyin-practice:v1:1:listen')!))
  expect(stored.entries.every((entry: { question: { instanceId: string } }) => !previousIds.includes(entry.question.instanceId))).toBe(true)
})

test('changing children cannot restore the previous child’s accepted results', async ({ page, mockAPI }) => {
  await page.goto('/practice/type/listen')
  await page.getByRole('button', { name: 'p', exact: true }).click()
  await expect(page).toHaveURL('/practice/type/listen/2')
  await page.evaluate(() => localStorage.setItem('pinyin-child-id', '2'))
  await page.goto('/practice/type/listen')
  await expect(page.getByRole('button', { name: 'p', exact: true })).toBeEnabled()
  await expect(page.getByRole('progressbar', { name: '听音选字母，0 / 4' })).toBeVisible()
  expect(mockAPI.generated.filter(item => item.childId === 2)).toHaveLength(4)
  expect(mockAPI.reads).toHaveLength(0)
  await page.evaluate(() => localStorage.setItem('pinyin-child-id', '1'))
  await page.goto('/practice/type/listen')
  await expect(page.getByRole('progressbar', { name: '听音选字母，1 / 4' })).toBeVisible()
  expect(mockAPI.reads).toHaveLength(4)
  expect(mockAPI.ledger).toHaveLength(1)
})
