import {useEffect,useRef,useState,type ReactNode,type PointerEvent} from 'react'
import type {InkPoint,PlayerResponse} from './LiteracyPlayer'
export function HandwritingQuestion({locked,onSubmit,onPlay,onClear,feedback,listenIcon}:{locked:boolean;onClear:()=>void;feedback:ReactNode;listenIcon:ReactNode;onSubmit:(r:PlayerResponse)=>void;onPlay:()=>void}){
 const canvas=useRef<HTMLCanvasElement>(null),strokes=useRef<InkPoint[][]>([]),drawing=useRef<InkPoint[]|null>(null),pointer=useRef<number|null>(null),start=useRef(performance.now())
 const [count,setCount]=useState(0),[error,setError]=useState('')
 function paint(){const node=canvas.current;if(!node)return;const box=node.getBoundingClientRect(),ratio=window.devicePixelRatio||1;node.width=Math.max(1,box.width*ratio);node.height=Math.max(1,box.height*ratio);const ctx=node.getContext('2d');if(!ctx)return;ctx.setTransform(ratio,0,0,ratio,0,0);ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='#1f1812';ctx.lineWidth=Math.max(10,box.width*.028);for(const s of [...strokes.current,...(drawing.current?[drawing.current]:[])]){if(!s.length)continue;ctx.beginPath();ctx.moveTo(s[0].x*box.width,s[0].y*box.height);for(const p of s.slice(1))ctx.lineTo(p.x*box.width,p.y*box.height);ctx.stroke()}}
 useEffect(()=>{paint();const ro=new ResizeObserver(paint);if(canvas.current)ro.observe(canvas.current);return()=>ro.disconnect()},[])
 const point=(e:PointerEvent<HTMLCanvasElement>):InkPoint=>{const b=e.currentTarget.getBoundingClientRect();return{x:Math.max(0,Math.min(1,(e.clientX-b.left)/(b.width||1))),y:Math.max(0,Math.min(1,(e.clientY-b.top)/(b.height||1))),t:Math.max(0,Math.round(performance.now()-start.current))}}
 function finish(e:PointerEvent<HTMLCanvasElement>){if(pointer.current!==e.pointerId)return;if(drawing.current&&drawing.current.length>1)strokes.current.push(drawing.current);drawing.current=null;pointer.current=null;setCount(strokes.current.length);paint()}
 function clear(){strokes.current=[];drawing.current=null;pointer.current=null;setCount(0);setError('');paint();onClear()}
 return <div className="lp-writing"><div className="lp-writing-board"><div className="lp-tianzige"><canvas ref={canvas} className="lp-canvas" aria-label="写字板" onPointerDown={e=>{if(locked||pointer.current!==null)return;if(strokes.current.length>=64){setError('最多64笔，请清空后重新写');return}e.currentTarget.setPointerCapture?.(e.pointerId);pointer.current=e.pointerId;drawing.current=[point(e)]}} onPointerMove={e=>{if(locked||pointer.current!==e.pointerId||!drawing.current)return;if(drawing.current.length>=512||strokes.current.reduce((n,s)=>n+s.length,0)+drawing.current.length>=8192){setError('笔迹点数过多，请清空后重新写');return}drawing.current.push(point(e));paint()}} onPointerUp={finish} onPointerCancel={finish} onLostPointerCapture={finish}/></div><button className="lp-listen" aria-label="播放读音" onClick={onPlay}>{listenIcon}</button></div>{feedback}<div className="lp-actions"><button onClick={onPlay}>再听一次</button><button disabled={locked||!count||!!error} onClick={()=>onSubmit({kind:'handwriting',strokes:strokes.current.map(s=>s.map(p=>({...p}))),hintsUsed:0})}>写完了</button><button disabled={locked} onClick={clear}>再写一次</button></div>{error&&<p role="alert">{error}</p>}</div>
}
